apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2023-01-11T04:45:24Z"
    name: dnsomatic-credentials
stringData:
    USERNAME: ENC[AES256_GCM,data:BFK4QaXL,iv:D5VMCEmM/zn15o3wx2u/DJFloCDa+Nnwlo7M1XqWCTg=,tag:/4dw/fcO9oNWviEdTZBF1w==,type:str]
    PASSWORD: ENC[AES256_GCM,data:ol4brT8DYXtk1QxGYfLlmzTS6w==,iv:U7KLrmFTbNq48FANlGKxwHdaUnU1TaIWJUibIScEFEM=,tag:t5FdBcRWasZ/rlBaMhcWBw==,type:str]
    HOST: ENC[AES256_GCM,data:a00qvtwXKQ==,iv:t5yl4pHFlVO2qJ7iVq2aoLVC3uIKB46Hjf5i/oFd5ng=,tag:b+mlAuziJmpfudf7UJWwfg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBtelAz
            ajFtVUVWNFRXdFVUdkllYS92Wmh2RStQZXpRUjhNNENkK0JkK0cwCjFhcVBXRXJw
            b0V1WDhqajhqVjNYcWxYRTVqTFNMUndLVzUwRHhRbDZzb0kKLS0tIDRFRVhJZUUy
            ZnFEblNhVlpuRnIxZy9nMzY5TkVyTzN0bDY5SXFRTnMrM3MKjRH1doQCcQmZhdu9
            JEFpk4j9VkuicFSsqrj1boR5d3SAU7rtFfz5fzsQQCq5/ItspHQn1aFlifEN49pa
            voCw+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSB5VnJ0
            bTZUajh1SW8zZFV4bVNsQmdjVVVYU3lQTFdFSUJaL09IdEZHZzBRCno0ZjFxNmd3
            ODMvc2dHN1lKdmorT0c4UDA4ZDBZWVd3SlFreDRxd1B2U2MKLS0tIEQxMmxxTnRB
            dTA4TzRBdXpobUtVTXhOL3BZYWxtTVFFWE9PR0Y4UVUvMDgKFL0Dj9gbhGFK3Ngy
            BjTMPhalO26bpQrRA+h4tgIQmdtzmGk+iYHsJoy6m1o7ZcsESsBVM7xvbKCeWbE4
            5zzuRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHJlM2hoOEh3M1VqaGww
            MzBLdXNqTnYvT2JLTDRwZkV6d1MvQ21NTDIwCnZTNXVWYWtpUUFRSnB6TzcreTRK
            c2p2eEIxR0VkSVQ4Q0txajZXTjY3V2cKLS0tIGtXS2Izdjl2eEFZSmY4NnUwUEpV
            clpySnR1NWpNSHI5dXR3cUxLR283dmsKdtskZVnm82xpp8XmJyM9ioh44U2v5FAt
            WCB0Zqcns9BxXzTNym8FH+cFVWhOwvApsbfNmr9reF5UUjSUbFu4DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T04:09:37Z"
    mac: ENC[AES256_GCM,data:IhHyHawk7AMb2NRiehF+J5kJrsDnCnqJUsnyxb0gow0j6z77DesMREnxygWlIIvX/1urxdDgLUzKy2dlPfdKxAVWXTjAuoqmlebqOMY3oVmWZBrjmag5rXOctPOPWG6KUs9atZdPJZMyZLBKeB0uqBryuS35KJ4venoSfruWO4M=,iv:5YHEctZgk/+5A8kBFzjXzbIjWDCUgZ8w+Z7HC9ShXcE=,tag:UgHJXSlqlhxtcStoO6AzIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
