apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2023-01-11T04:45:24Z"
    name: photoprism
stringData:
    admin_password: ENC[AES256_GCM,data:thJd0gi6L9y7OE0iPrbcIw==,iv:yCwcTaiHsQp1ACm/BqchjXk3AOMtlWCAVL/hHmysCBA=,tag:5dFNmo/qtqZQMy9RKPRhlw==,type:str]
    database_password: ENC[AES256_GCM,data:0Sayy4WqxirjTHekvz1UjBP4NQ==,iv:S7P+BhA+ImdR581NW7nBfeOf5RFAXTeU1sbI+o25RnQ=,tag:JbGnQ+jIUVhp+5aNs0bCYw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBjRmNG
            bkR3OHlPd1g2Y0lXTmIzazdlNXhzUHhJNmxmME9KK3BWOG5CVlRnCkVYQzN6MDc5
            enhmajdhaXBMUXhZT0xYaUgzdXpjVVZHZ1JsRUUyUi8rY2cKLS0tIE9sSWlCMHZN
            ZXZJN1ZielduMHlmQkJMM2JzSzEwRWlPQzRpVlBoZXRFZXMK+6M1dVWicWCErON+
            wKVLzw22OiKfYZWCMDaysO7Fk5xXsW1rDZ+AQwTDXbD6OCrwiv1bM+FCtplVsQAh
            W4GSUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBTUmE2
            OW5oZ055d0Z3RFp1bWpBbmJTRDJXVGljcTJtMHgveDB2Ykpta0djClhkdlJhc0cx
            aCtZdkUrdm16eEJKR3krQ2hteHYyR3pwUkhkdFIram4rV2cKLS0tIDYwaXJhVGcz
            UFYyZXgwbUx6VFFMcHIyYUFMckVLMG1RTmFlanUzektmMFkKVhHaTRlVq2eEABjs
            8k4jzSsVvk/n0Hknfm9UmrYjd9EUwJiJ2vzP8p27E7z78rxCiRWMVpzOLWmKhCBL
            6Uyo6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb2NZcWJQSFN1S1owaWRn
            TWdNYVBFU3QwWnY1d1E5b3orR01DNWN6VEFZCm0wWHR6SDQwa0FyOHlLTUF3WWhL
            TWNiQk9BVzFnblVXcXB3YWJBUVFTRG8KLS0tIGFzemFTNVJJcDU0SW1YKy9jeTU3
            cHprTjZMYWN1aFVnZFFRYlJpNkU3ZmcK+ptRKVfKc5vH53eFKGNU9UHXJH9gAzuF
            3FHWEOntmWirs7Qzv0k4Et+9bOItiRfyZ61hxKFLAPYbpwpwp1FrmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-14T18:08:06Z"
    mac: ENC[AES256_GCM,data:A2RXjbn7d65sTRkbg4QzjHhrFnDlSfUoHK+CQrCxLl6zdJgvpgGpBnTC3ti+pAvTew89B/H7dBH39773kt8PTl9qF07EVYCZkHhIq86iAzkbClNbiXekMp5Hc/kOQDfh9LTtCCvAgKPnbLyK43RC8XPUaBpzRO/+WMFFkHtthQE=,iv:LHb0xkDRKw5kPhYrkJ/HggaybJ++bWwyr7nxWx29cqM=,tag:CHPBzahOEB6QCWKGooj8zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
