apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2026-02-24T17:18:00Z"
    name: headplane-secrets
stringData:
    cookie_secret: ENC[AES256_GCM,data:U+xqjfYmABms8VzJf6q6aqAA20akMVl+Pjl/yQbzWEk=,iv:hqybppE7ZJiC1ivJPHwx+hjzrlPCldaIySd9dg7PS7Y=,tag:4cyCRfbyaqPCiZvGTXMsEw==,type:str]
    pre_authkey: ENC[AES256_GCM,data:cotKvARBcUOd+h1wls2315lEJeY7cu9LuV9QU9v0ugFDeQdo/BQ7159928gtynbV,iv:cEi/qtSOutIOug908RHZ7suk33SoTZlHitvqEFrxz/8=,tag:Aco3aZrSnaLugwuI2mmEDg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBYSnAy
            QXJ5eWgxQnMwR1dEcFBxRzJVeDFZQ3lCSzdxQVhFQy8wQ2JXL0JzCnFKaTQ1dUFU
            WDdhOXAzdUJNMDYzNlIvSjQwdUZLV3U3QWVvZno5cytsQ3cKLS0tIDk5TzRBV3Vh
            M2FyNmVJUVdaSVE0dnd0eW81WUhaL0l3Z3VFeW9IcmZETUEKo8t05wwoR/HiDRyy
            mSjdN/+DEADY31I/9Mg6O/mpOQb+LzR6m0OJXGztuIGm/QnpsKguDfxJdDz1gZkZ
            psIMaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBSR3p5
            T3pVNGoyNXhhSEJibktEeEUyVzFnMy84U1F4amtUN21DTENGMEdrCkVoaDdINUFY
            MkFKRytNWmZnNzQ2Tk1IVmhPZER5MUQ4S1hETzJMbVJJQW8KLS0tIHpKRFYzeUF6
            Q0RoWHpLa2ZBNUpnSWlMTUZQS3hlU2RxVm9IemtoU0ZhTUkKneRUHh2dB45KQvcR
            k+mGAerHgotzJpaB+b6Fop0sd1vwUotAGMeOP3ZJAu6Vj9A8BRkomMbO+JoZc6I3
            vn/EnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUWZqWGx6R2ZtOE5oWFJ2
            ZUdRbm1PVUVxUjhjZVoxelgyc2VnWXZjWGpnClFpQ3hQUGp2WnJNeG5GNXU1a1Q0
            YjU4enVFWkU2dzlMSHBGR1hNMzNRK0UKLS0tIE9PcHM3VEVIUGs4SkFXZE9QUDRB
            UVVwNENQQnJ5L2MrWGVBbWVERWNyUFEKP8y8J2tAruLQl1FuLi768CjKwazkVUO9
            5OWKe95IvLnPmREDeWxv5tRRPkF7b1C1CboVeKVGbugn95ioQa65og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T17:52:35Z"
    mac: ENC[AES256_GCM,data:PJRAXp+XBhhwDVCbmAULWQb+LXVrZDilPJop+Xs+cPxdsLHDx/jyAjuix3FL/Dl37uchV3ozHETxPH6g4uszgRhyJc8483HfUKsO5OQjHk0meaJze6C9p64XkvmAQhuOejVjMchuCZKlx8vp4HqMiu7v0iiBzAGiLMyamtwld7c=,iv:Vt89RSSYzHei5FlPBqquHgdLuOnMwCc++sKj6BNIrTI=,tag:9qLXK7zbn/+3rqZCKZqt2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
