apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headscale-config-map.yaml
  - headplane-config-map.yaml
  - headplane-secrets.yaml
  - data-pvc.yaml
  - deployment.yaml
  - image.yaml
  - ingress.yaml
  - rbac.yaml
  - service.yaml
