apiVersion: v1
kind: Service
metadata:
  name: headscale
spec:
  selector:
    app: headscale
  ports:
    # Headscale
    - protocol: TCP
      port: 8080
    # Headplane
    - protocol: TCP
      port: 3000
