apiVersion: v1
kind: Service
metadata:
  name: headscale
spec:
  selector:
    app: headscale
  ports:
    - name: headscale
      protocol: TCP
      port: 8080
    - name: headplane
      protocol: TCP
      port: 3000
