apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2023-01-11T04:45:24Z"
    name: rclone-config
stringData:
    conf: ENC[AES256_GCM,data:nJew/6T2NPHFyGcw8R/L9HIy76gXPIx16lg7AKl+jdKwTb9QfLXRIoguAIYiyhgPfCY3JYlJEhAICLUWajg02gkWYrJeehASG7p0QB42caiCulqROJgiQrLwZBkXH5Qul5yFVziRdMX7en3854l4ycJE5RzWbNQl3LJmmvRrnHeA4w61F53LOfggyDpTYje1Kgm7DdBL7RpTv9SS+YrxYCr505Mj07hzaXJamuEib4i9x7RMRWfKD0D+gHdhXnFVPYMDixcDmCRY0WwT9KJL+okVtrWGKn1wCd9tK1dvh3/s9YUiznKFJKhoact2cjD/nNFRoo+HupAj8/JL7B0kcS+ucM2HvxHwSZo0v8ZDHMm/iutY5kU+qpWtaF0wvhm5VQkA9i5a/FVLZEuZsgmEdXUFdnWbR6Q1XKpUBibj1f2OD5crN34/AauAu7M2SSzAvB0WemPVJ/g1GvY2Cqe6OJGR1DnRe9DUzNBcKJTIvhfl8NqcchKjXvs9z2MZCXGrJVchQnFzjorxDKnZhOE4Qeu5iwQxS22zK2Q3Sf8+Cgz5dq3/ZNenXGkOvz00bAUC0pHGfpGfbkIhE1UR6LUScfrQjLylOiZE3Zl5Ntv6OR/hO8R0ZJBv6dvayEvMAXaDs1K/eIuBM24x+sauzevZs4teym05baxVQStmlyVrdhGzMZ80JjblxcVE/PYm+9j51w==,iv:t2I0bMvQmMkKkti6g9H0rPdDZKNvgSYUnx5TW4GAUMM=,tag:+tqduQdQKjhlv8uruaOHMQ==,type:str]
    b2-path: ENC[AES256_GCM,data:GBeJn7Bk8Q5kuvpxzhWyAiQPN31c0iyMPjkIU9A2MQ==,iv:PGdLV6NSYIe5wl/RwO2KJh1CRt3XOcmvfKBFI8wqrtE=,tag:5WdFKwpRiLCi8mJgptd0CA==,type:str]
    dropbox-path: ENC[AES256_GCM,data:VeZXGXqf45giuFNhPBMsZoNNkTirYrA=,iv:BdRrTpgIBgoLC8hwnqWj7iXQN8IShKGtgWYLSf5iv1Q=,tag:pdBFo2psBUviiwRlxvreVg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBNeDB3
            aFY1ZVV5S3lHVW5KYTNBeFhmOXp4bnhQL09wcTZWd1NmSmNJZVQ0CkVpVVFKbGFo
            Q2E4dFJsalp0Z0VYQzNSQVB2WDJybWJQVFgrTHhLNm5aRnMKLS0tIGs5Y0Z6ODhr
            N2JPTWh2UUVVRUd1ZFFuU0MwYWNpRnRJRnEwYlI0cFF4NG8KgCvtR5M5tYaQxmFd
            xaVm/kaEIhXuVFFy5rXe95h+otlKIOxgCTtY8nNP4x7ZYAmpZgK/UymKXyq5LZ8w
            tScSoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBNbDEx
            alFFTm90RVYzWUVXaEpsaGlNckMrNWpZWWJIMmhSclhCczVlNWpFCi9pVnUzc3Zs
            d0Z5RW1nWTR2SHl5Nm9CRXRzZTc5YzVPYkV1ZlJQR0REYW8KLS0tIFhGYytaN2wr
            aE44MmtmNUdmTWhvUFByR1BiVWV3OWduWCt3ZEVqemEyRmsKVtweNbupTWr7v99w
            3zV0ALxUpiM0XgqLDuMs2Tvgoeof03Drw9yzbw4vibOl+J4VXmHkdDzKvjF9i/6r
            20Tx0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcmgrMGttcmRQRUYvQUQ4
            WXBGY1RGUVdBZExkNjZhZnpieFZqTFNCYlZnCnRtdG5EWmRiK1o3eWhWQ1ZES2Zl
            VXh0Y0dVQ3pXbGN5TStiVHBJV25FSW8KLS0tIGFmRUNLWjErWHpWMW5kd3FhVGtq
            Uy93cWlqS1hiTmEvQmRpYlZuQ0N6NW8Kf5DjCqUZyGH4daAnEPV1OFDa/cLPHj2J
            Eq2Wyx5i+xYzqUFMMhp02HsNz9TwA8DYXFt8JmgM5SNcwM1DXZ79/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T03:27:55Z"
    mac: ENC[AES256_GCM,data:4vnZfJXR395LCFHpuTGoUF9hR+NgXzzMbiu1N/OS62epiMoS7vPs3zuN5kuWrYH+SrEJfS8tJLcOZek49jETJTBgj6Gyjien197frFdr3GZE/49Pu4/zxy6d/z6zKqEeIcw3CjlaG7kcvsL5pbzcBqxWxcVrQ0epA2I6DS+0TfM=,iv:QJFIGpcI4Il+odvTpLX7RhxYGr5ugn4Bd1ZSYQ0Ox24=,tag:xDJvi4E6YgsvPdDuNu9X7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
