apiVersion: v1
data:
    password: ENC[AES256_GCM,data:rs6JyJ+oo4sQEbkV,iv:xPOVIC3zp+7Mtjfp6BSrpIpNF1vRP9nTdTtfQeNYLd8=,tag:IEVIY4JIA0AgU1Hf3UNzVw==,type:str]
    username: ENC[AES256_GCM,data:4gXAd6zbCO6CFOWK,iv:3l6m//ohlr9LqHBzOfkKDIWu4Y4xfviauCTDxRahcfg=,tag:+WIxA3XAsFXitU+F6mD7/w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: smb-credentials
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBzdHhV
            cU1EcG5rbXV6WStqQXJJQnU3NTF5ZVFydmxjZ0RpbzZLMmRIajNJCjNoc1JGS2Zu
            ODZ5dVErQ2FYcjdkblNDTUcrU1huOXJnd1E3OFprRDBTWFEKLS0tIGlpWndNTnNu
            NUp2ZlZoQkdGYkJQeEZadWNCbzByZlNDbHluU2pYb3l0dnMKWYefwL47XYuSw4EY
            j869Zcs0khJiQR0a9EogbsyUXeUf1gtax8gjjfiPKf9QLtrKkgckPAdPba/HvTlM
            Wa7bFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBUWDhi
            TGRxR2ZmNUNnMG8xY2JQMUpJallBWjlnRmFjS2w1M0k3eTN6UmxVCm9ZRmVTOU1h
            OTVoZHptWFovUDNtcmI5UFdTdEF6WEtVRk92NDhLdHhjWmsKLS0tIEhodjlpZVJx
            Rm8zVmt5aFJaQ0RBdS80T2IxYStoc3VLQUFyS3QvWTNLeWcK4hTmt2TG5ub+Pr9c
            b7YHQ/B5ccKy6/LZVaME+qWO3gaeZjweD/EHtklqhu9IA1tCzVjXU+DghFuAm7hU
            fegSMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRFlrL0hnTWNMZGRFdTRs
            WkdNNXBUdmVoU0RqdXBOaVZyMXMyQVZIYlNzCk14YXgzNzBqUGp5R0dVSHhGaElx
            aW4vY1BlNlBoakVQQ2Q5cVdHckJkWmsKLS0tIHlkU2wzRWtIK3IvSW5QRkRiM3RS
            ZHd2bnVaSVFTTnJPS2I1Y1prdi8wTWMKrXhsJRVxd46Ow9RBJsNZQHP/bdszppE+
            pmaEIyD2kbXUHdPvtITfZD6r1I5LomQVk1bScgCdaXBp+PBy+U7+hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T02:45:17Z"
    mac: ENC[AES256_GCM,data:ZL4s++9IQIyWjqJrYbPoZUkJHeeR/OyuIznX8SoxVV/qZH4H7MoL6/XQ+0281YLFgGAJBncBQGbZFIUBQxb14HmG05syn0+2HjS5+KHqFAQJlNHdL9MDs8p4gUzTkHMY38OsLz43/WM/yVF6wqmGo7kZ+buwb6f3J9/Tx3aQnkA=,iv:Xx7uEOKdf6Utyk0Rqy1Kk9GFVpth+esS8jEeCQYc7rQ=,tag:EFqrX8AtH87Syst93QRwIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
