apiVersion: v2
name: photoprism
version: 1.8
description: Packaging of photoprism app for multiple deployments on my server.  Presumes openebs, ingress-nginx, and a secret file called photoprism with `admin_password` and `database_password` values defined.
type: application
