apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2025-01-01T17:37:00Z"
    name: plex-preferences
stringData:
    Preferences.xml: ENC[AES256_GCM,data:xMwVJd011hYQ184JGAnLouN4QwunS9+DpLh25O05Mj8BQwfhhlu41xzEeXVLUl4tGv9PUpKkqwh2axVe36Fhw1TVrcC/HwdpUZFriE3QxYDqwJicK/Z3CRSYKImmtkpjmI9P03HdsAqIDG6t1fcsHiA/GPmpLbxHcN96zpR2JXusT9s4A711U5rlmF2ruGSZwjvsTpbud982ca0NEqxaP6dzI7jd8r4daALFyFvGYGnPPLDWURLwtt/nFrCtixiIGo7XlFNJDWt7kSK2ouuqMxhMiIj6VBOIb09BvDOI/xUhvqowNMR5MTnOaPhmeIHukjI5uy5iM3fiCIhEjdiFxPGwNnjgffldabkMQPTHhHkKWE7kY648BmQDbZ5XeB53GehcihgNqO0G+6GDkOqXPxFgFk0W2Mo9yin7apEx+iownZnuSA9uW696CgEzJ+KAu5KPUaesVNOfmQsqUGnLm13S5IBLntLO8mqGwcMewBPMkp9flS5crouJWT9VvktMP280FCv+aOVRsT/JjVrRqbVcNMIWJyRzaZGFiyuKx0IPlO8QcBDRkpD+WYq3GwhBphs9da+HZsJarlao4O5qbfO+5W+lz5HSxJbY8CuI6zv+/jYSq4qilBA/JH/LwKClYvGkCcyd/XYHXTN+vXG4xp6zrP7QZIGmdYILM9YysgZkxWFuXNwZjojKzJt2L4elhCGaq5AC8KDY0d2lMauD1bjwdFIJHrhG4Nb1xulboWKvbUrjNHOpZm0+GHfXPSYNQPti85HhvePgNVJkm1ESLNu+5ejBU+vSbS/mng/L8YIzSUxwt8yq/sKTVtydhBsQVTR0YILKA2hgpsWRT76jSlxSyL/tOURrV7PnJYqe9UHyZztZU5pF2wma3htNfWz7rjD738AvYNoWfjUSOaueE3z2ozq7uiLKd/wGJKALzNXtWLtEvStnUJqbZTrs1cEBohewNCLWTWQm/jRDInjIbHsapl4BlSPr4tK3Pjb0fEos38GQgxaypx/5VOaZuE6OiwT48SWw0+JnJo2e9yz/7Lfr45bODdnZq9sCDSkrWQB5kdsJyXbX+vRF2+N7XuuDVWBxzEe2roLsDJg69f6KQwnit2p6SkH4QYg9ZwXg/zFzxJAeI4jHHPWM4qwGmBzq2/Sy+WD4zt0CUenDbhWlpNK5bMM=,iv:Y4mjfoS2IoUM/akqTxKUeVjc2xCVWT3bF7ENel6eSQ4=,tag:i5boR3ZOidUWm+V2yuj5KQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBHbnhQ
            cHE2Tk1kMS9wVVBFZWpVdmNoRjdRTGRoQTQ1bU04eDBsVW8xNHpRCjVzS05yMzR3
            NURjQ0lUK2pEM3RpTGMvNFN2bDZXSCtUMVcyMmdMeTVMZmMKLS0tIDhkeEhVSGcx
            bHh6SHZjVys5YlpKL1JFMWpoV1JFZTk1dTJXYXZXK0tRamsKZAPl3v1I4tvgDxbL
            f9GnAVaQVTbM3W6zSB9xgS2VyTuNBZx937GA1avDMD9fX/NMZ0+OTXl/dJtLA1vm
            XzQw1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBXOVVH
            MTNYSmRLTC9VamtvQVpjZmJ3c25rTXJXVWFhdTVjRzRaSjRBbVJvCktFVnVDdmxK
            LzN2eFBDZDZjVnNpdzlmWmFWRFFtanhVWnpvcGhmTHNXRzAKLS0tIGo2SWh4cGtS
            bHVtdzFMYzNuU0EwUmF4NlVac2VSbllCQ3c3VmpWdk13UmcKB+LPOda+jdH/sOKZ
            sQevam+M6p/V5ma3871l+jFC1z6/SGGq33+SZ47q4Ss4/FXoRMiOvSHkm0cH0QmB
            T82wvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFhyaE9CTUg5Mld3bitT
            U3M5bGJJT3YybXdTRzJLS2RzYTNvekJUbFNrClVsZ0N3aW95ZThzYzAyc0Vzdm1w
            dmVKcDQvSVV1ZFByQVdnWVZsRDU5ZjAKLS0tIGF0VTY2YkFJT1FWU2RYWDF2bWhJ
            REMrUUVxTDlSOXRHNlB1SGVqVlJ5TmMK/Pk2Hk/HAOQfSHFvjAWjBYhQsbgp3jxf
            I0/6lFWr/VOWBEncdCkWG4RpIm9wiQY/NQlTBch4Di4QdF794UPoVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:48:39Z"
    mac: ENC[AES256_GCM,data:GBO149R3yRtg90tGvbJRxqQPzYgaZTwb1nQThbbQnne4FjeJ609gs9VN2jCnqW+mKDD8zO5I4XgIKta/2TrW+u1/nvbn1Z46Y/VS567WVMqYFQeVYdVjQGBJl+UiQtUdEY5r3WEu1ur4uZEiq1gwrPQAYCkxP0a5c/t0Odj8J9g=,iv:FhOgFbxpjuewR1XLiU8UIfJGnKJ3A7ClYy9gJcCryZ8=,tag:tVJmzD6vsayRl6qVgNo+PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
