apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2023-01-29T15:41:00Z"
    name: sftpgo-credentials
stringData:
    username: ENC[AES256_GCM,data:XmmdiDQViZQ=,iv:1+X+jac7Hb8jcnGc09QKdCTV8QKpj9wEq9E9Vcg58jA=,tag:YvYq6udeRSztWK1mgdtBuQ==,type:str]
    password: ENC[AES256_GCM,data:R9WAFzd6xMd1cQAJVhfF/20Ikg==,iv:r7kOZoEq8zLcdV7Zz1cwAApcr8SKiJyYl7nlRclwJmU=,tag:vyywLcVwJC9gOOF/eVeBlQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSB4WjBZ
            WDBnV3VZVjJRSTR0YXN3aDc3UDNkSnllOE5PcmhWc2FIM3N5QnhVCnZFcCs4Vjk5
            SndzYmtldnBmemY4c2Z5WkhmbDR2M1B2OVVPN1MrTEQyOWMKLS0tIHNVS3h5MXY4
            ZGdXblNkUm5PT2ZEL2lFWUhCOW5GRWZKMXdtVFN2TjJIYTgKQZAKeSvlnMBtQq3p
            ygb8twwdwGPc8uqydhdEO6c72iQZOodJyRkTLXFyf6XrA5+tngZI6hjWaYpt/oAa
            Z03dCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBHdkFX
            Ri96dVpyYWI3RmFqbmgrRU5CRHVlVUpRbFJOUjY3Vk1CbTd3TFZ3Cno1ODNXcjdm
            d041RHhmdDNLVTQ1ZTNKNzl1Z3BuVTkrSXpseXhNT3BLRjgKLS0tIEdpSytBcmla
            VGVPZi9WZGxtdHBHcU5Tazc0YmRtV2hBcmU0dTdUZWVWSmsKn4YYuT+RW2Bm92w+
            eOlmdXol/6vIqeDcZJOXFVwV5e4RxYsdeFtw4xkLSSnt3VM9ENm/meaekK8UOmD1
            6wNeEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM0lveWJRWXJQUHpDZ0pL
            WEFNd1oyVlRQTHhVUDcwZHp5NnNMTC9xQTF3CnhxQzAxK2wwV2M4U3FSQlRBT2dT
            N0ZEZHk3a1FUWE8yU0VMN1RNY3lnbFkKLS0tIG5Pem4ram0wY3NnZHVnODVYNCtJ
            RVpxbkZHbk5xQnNQcW9xck9OVndTN1kKnMHaxdQiWK2/fueRcLhZGo/TOrC3wwXx
            qCvS9QUCDd3y3pRzuPvxho+3nGol7RdZVKmO+NxoP1pI+NBArg4M0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T17:59:47Z"
    mac: ENC[AES256_GCM,data:fd0CxL2rMcLIhK3wJMRM0GBk4QF3MDrj6sQMY5TwKb7/ucXFRln5Hh6GQeCO19RPIfsZ0rrugERM/imt0uhU0y83Q31b4aF/5+qYfqokHDgk0A61bCW1lNBmWgAcof4Zy4l55jEgSmFLWD3IRiQk2tSDxlkRCF50dOGylIMiPpw=,iv:+2p5MxjplDEuBQ5G1eDjM7cNkSUQwiqJmQhh3FMyDyA=,tag:hxfG38ifFVJKITMA9m5/8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
