apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - audio-pvc.yaml
  - borg-backups-pvc.yaml
  - borgmatic
  - beets
  - demo
  - dnsomatic
  - games-pvc.yaml
  - mumble
  - namespace.yaml
  - plex
  - photoprism
  - podbook
  - podgrab
  - podinfo.yaml
  - photos-pvc.yaml
  #- rclone
  - rancher-key.yaml
  - salamander.yaml
  - sftpgo
  - syncthing
  - syncthing-pvc.yaml
  #- tinyproxy
  - video-pvc.yaml
  - youtube-dl
