apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2023-01-20T23:14:00Z"
    name: borg
stringData:
    password: ENC[AES256_GCM,data:0xDRZPp85CDH+jwpzytEqtwrzc8U7uIWEkHSYbPLfLE=,iv:iqQF0BL2Lq0Rtm1+ahfEsvXmUhrD01l6XNQGaKOHe3o=,tag:pMx8MFP/1tvRsQwqupW0Cw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBXeGox
            TU83YWQyNTJ5cVNaeVRvQ3hnaks1eDVndmpXRU5Dc3E2T2tTZ0ZnClh2eFoxdUZC
            T3kvVHFFVUNaT2tOY2xWVU03OFV4YjEwL1dpVXBRNExhencKLS0tIE1wYjhHaUFV
            bEhaUiswV1NTbTc5ZXNGY2JKMzBSMTd3eGNQTitkUkVEWG8KFmCj2C+97KhSdUpn
            M6O9uk43GjNSxqexRRfJxZmwNCM6Bs8L/h7GdQggwjSwPTcnRAhwygehP3mcIE7e
            71VWXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBFSG5J
            OGRzN2FRQURlc0NNL09zZXBGNFp2cGgzYjVDeWwzUkI2aEFUZ2xBCnZ3d0hBSFNE
            emR4R21NRnEvMm5od2IweVk0V3pseTRTWHltWWovOXdjb0kKLS0tIFlnNjU1N3Ix
            YVllcVNPZmpTMW9iL09YTExpM2JjcEoxdXNvazJyRkkveEkKe1wnihqRZK2dsazt
            z3efEHUzAd4iXgArxl9tNe62304NO2XAq81znhdTRB/DnRxarTRKrkrg63sWGsdn
            SLnVcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMmNGbFZVYmhuaXBia3pr
            ZmFwUUVzYjV2NUwyZVcvZTRVYXRvS1c1eVNZCkhENkk1WTJZZFpQR0N3L0ZLTGdo
            VE9xK3VVMzlmQkdQc0pvRXFDVDh1SUkKLS0tIHBwU0NYS2JvU2pvSGV3MFE0QzFN
            RitGQ0NaaElBU2VBWVlRUXU3ZmlPYjgKpwSokryLuW7vcWjPPyres19nyj2trJqC
            P5TcMJu9si6RKXaJ1YnBtOUp3issIhuNa5+00pQFYEbz6LEWqBJnFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T01:14:42Z"
    mac: ENC[AES256_GCM,data:imnpJe9ulhe6gM58s//i6S7Ms8oKTycWJQhZQZShvaDBku3xpjaHjusg5puOK4cuF/H1hA+gP7/ANR0kqKnIfdVeKZFnnmQLyrAxfmlxZU7ewlvhzbUaQf9OD207AoDErMQJmcNxVyBIh8hrHCJqIXPR/1x6iS7ZR3VXmBuSykw=,iv:ApEzOUl0Bpfq9nvXK3i76P6Qco91lT2FysBWIb7Uajw=,tag:h419v31opK3+rE5qmOEoUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
