apiVersion: v1
kind: Secret
metadata:
    name: linkding
    creationTimestamp: "2025-01-12T09:16:00Z"
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:A1JTPw==,iv:HseZXNaFYbuLMn42h5hngjdyh6kBB6PGXrjxvCQCEoQ=,tag:BJhr/4j6BQY/UHZSCmciKg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:u3gLAPjnJF7M8DLL4kziKyfp/VP+oFsa/4qos4qbGkM=,iv:U+eQvL97xmZiu2jF+iC8TbDKVwkc73w38RNBD5qqr34=,tag:JeTt0Ulj6db79QeMmqik2A==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSB4LzVC
            eUFnSWdodlAvNlgyK2liN0NwdVFVd1YxTGdLVTlEeU1ndVQzYmpRCnYrRVlEMmJk
            ZzdEWVY2K0cwOGZvNE1GRkZDajJVb3d5RHdzT28ySGQxSm8KLS0tIHdIeStQc3Vi
            MzZlQiszbitCTEtNdW9keFRCdjJYSHJHN1Z0ZitYbWNnc00KbGjqdVl5QPIt3NBE
            +OlRps7SvIkg307rNPWCpkaqlYTxxDi+wuVVxemGcA1Xswn70Zs5aitfxXbJwE/f
            uC8svA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBuV2Qz
            N1YxWG5JeWxiQkdTVGNucmdFNDRxOXlJMy9IdGNzdHE4eUlVNkVFCmhhdWMrenN4
            MVlqNzVaa0hMd2ltQVZyVGpycXVQa2JubUVUZFpiSEg5K1EKLS0tIDhzTVhPSStW
            dms0bVQvL2MvaFpiVzV2aElKMUdBUmRLNm1iT0FpY0ZyTzQKjjITYj/VxkQCbkWR
            A4gZdJmeiqukj9VAkSGqw6WItnRkFSGqcTnFagyQFfTra/QaDh8IgdeQmvKAogP2
            wqbtIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNlBaSC9LUSs2M0NsVzg4
            cWdGSWlFMm5ObkQzZndmcnB2MmVNcUp0VEFvCjhSRDFVR2ovNVAwSFZGSGVHZ044
            M2FGdTVvb1N0UlVWekJxUnc3M0wxbkEKLS0tIEJTbFR2MWVwYTZnT1k2UnVhU0w3
            Qmx2cEl3ekNpM0NkWmVEb3BST2pWMGsKwldqTdLmB99klr229nyrulupphtEZ1m2
            S7qZgzl+pFBWSfPyPH2aknedqmLaqPxdn8thkcAlVpoUZUMRWNBVJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T22:20:35Z"
    mac: ENC[AES256_GCM,data:NWfPqBnCx64fI9lPFAiJNyC6U532+nAp727tx8Wea+IHWpbki8k6AYBUJabaN0+h9L2RSBifpy7xc/1YMKyvAUYT8rHQJ1PU9bnCJo+55b2LcFL0BQd5z4s3d+LRIp1BJwg0ezg5L+8ofXI0BVSk0wgrDykrHosZ/i1M0JPw/Y0=,iv:id6O+EkqDoWVWIrisvcgcEUWgYWbl1P6aiOtc5TBmsY=,tag:9jVlzsNI5oWbiHdNXbRk1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
