apiVersion: v1
kind: Secret
metadata:
    name: podbook-rebound
    creationTimestamp: "2024-05-25T05:54:00Z"
stringData:
    UUID_NAMESPACE: ENC[AES256_GCM,data:4Ut/JsUu1aNNGgphGqsBqO7s63qW53VKX07hIoCHALhQXkMj,iv:tSbS5Qq5DAQZyaElXK0UZ+a2zZndgwhpS42wThWPL8Y=,tag:lIcloebHDfRebF4vRu5zQQ==,type:str]
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:NGfTw77OwuI=,iv:dHD8ua+4IwXbqcN9+sqiiZfQ/HpAH5RIIuS1VqjNiZw=,tag:kqQASG+riD23YmRmx/fNsg==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:xqscbLMhyMaQlrsN8BIiPg==,iv:oto5UnRc/lRYyjS+8Py6NOVHSt/SuoTbPEdPolAtgPA=,tag:EaI58RRL5Jqc1+j8qatUIQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYSwODOrerKkBNuitwqjNioFXLDRBKqSJTayFoo1Ude
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IG5iMUw5QSBtT3pX
            SjVmMWsrQU9hbi9YUytHaE1ILzh4OTI0UEJxeW9rZTQ4N2NYL2p3CkdpTzJWSG9N
            TG0wMi9yTHZNM1F1YWlJY3JzVDZ3c0JORmlXeWJzSFNrMlkKLS0tIFVaV1RlNWZR
            MUlaRFpUdVlzVlhlOXhGSjRTOGl5TTBlek1YaVNjc0RNdjgKt8IbEktxS8T4ACRz
            JFy9kECnVhVYJx2/HoTX2Htkv0odntJ544FfOPv4IpsQQZOV9LCxO45ob0dMTJcL
            +cb3Kw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIyPkfTI0io9dZsJstcf29tddyrsHr9bnM8UXKtaVJwm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEMzS05TQSBROG1l
            OG0rQWpweUFOU3JEN0ZuV2Zoa1VLWGVLc2xnMTV6T0VoSkN2aTBjClMzRWlWc2xU
            bE9oaXYxakZaTmpraTJsR2hTWjNiRWRwUXJVdVNOZ1ZyTjAKLS0tICs4R2g0TWdo
            ZUd1UXZJeHgzamxpNDE5L21pcGd6UGVMQVRpVXA1WWpES28KhnnODrYzaOmpRwmq
            fd3npHKHkYP7iDMHjYHB43hL1/uEhtQxa8s6viYzN/tI4Q1zz+wqjWIiTMCmr+MT
            BPpaYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rkkc3rmwczelakcy57fh3schs5qv6488hujf9c9s7zh3jpng6acsxuradu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VGt5ZVdwMnJXblZiR2ds
            MmlDK1pjL2wyYktoYk1hYTIzWjRBdEFGb1VvCjR5YklJanM4NStuTENiTndndG5W
            OW82cHlsNE1TSGRUOXNqWGc3Zy9scEEKLS0tIFJMU0lJQjZHS0JvUm1wcUFxNW1z
            OFcrVDBkNTNuQjB3eTltQ3hlaDloencKLGzkOMUfNZjIlTwT+2u4He0PpjjtfZbt
            iP3GEXqEq6r6PY2uajuWuOrX8xXEKj08135QBydJGesuoCj/Mh/kKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T06:15:48Z"
    mac: ENC[AES256_GCM,data:u0mLyEQLKsXSLfkF5wr5lZbTNEFneHO2gxYsPCwllAWCjNPKvzZ7PYAGyhRGhS55uTLbi3U8USHbYz3AccEdK8Ft17NCQj9RY+R4QpY1a1Xri6juA80l3oxdbWWojkH2UA+ZJ6H5GQHM2+s96xMU2hpCJtFsIZSI5xFiO8wpMDU=,iv:Pm9NapVxOiKjTRR4wk2VfHBYGeanMUqOdryCW0LO7yA=,tag:R5InqKPTHTQ5beTV2B5dgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
